// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ljualqwoexkjhrwbizkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqdWFscXdvZXhramhyd2JpemtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTc3NDksImV4cCI6MjA2NDY5Mzc0OX0.F2z7i2rxGmXcb9QyGsy0K0TjDAioEt_pf4H3p4T73w8";

// Create a single supabase client for interacting with your database
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);